# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170805_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间'),
        ),
    ]
