# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_article_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siteinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=20, verbose_name='站点名称')),
                ('site_detail', models.CharField(default='', max_length=100, verbose_name='站点介绍')),
                ('site_logo', models.ImageField(default='image/site/default.png', upload_to='image/site/', verbose_name='站点logo')),
                ('site_topimage', models.ImageField(default='image/site/topbg.jpg', upload_to='image/site/', verbose_name='顶部大图')),
                ('site_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '网站信息',
                'verbose_name_plural': '网站信息',
            },
        ),
    ]
