# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.CharField(default='', max_length=100, verbose_name='分类图标'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_footer',
            field=models.TextField(default='', verbose_name='站点底部代码'),
        ),
    ]
