# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170808_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_detail',
            field=models.CharField(default='', max_length=200, verbose_name='个人简介'),
        ),
    ]
