# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_userprofile_user_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_click',
            field=models.PositiveIntegerField(default=0, verbose_name='文章点击量'),
        ),
    ]
