# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170819_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='site_contact',
            field=models.TextField(default='', verbose_name='contact me'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_links',
            field=models.TextField(default='', verbose_name='links'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_powered',
            field=models.TextField(default='', verbose_name='Powered By'),
        ),
    ]
