# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_siteinfo_site_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_nav',
        ),
    ]
