# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170822_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(default='images/site/default.png', upload_to='images/site/', verbose_name='站点logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_topimage',
            field=models.ImageField(default='images/site/topbg.jpg', upload_to='images/site/', verbose_name='顶部大图'),
        ),
    ]
