# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170822_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(default='image/site/default.png', upload_to='image/site/', verbose_name='站点logo'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_topimage',
            field=models.ImageField(default='image/site/topbg.jpg', upload_to='image/site/', verbose_name='顶部大图'),
        ),
    ]
