# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170822_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='', max_length=20, verbose_name='图片标题')),
                ('image_detail', models.CharField(default='', max_length=200, verbose_name='图片简介')),
                ('image_path', models.ImageField(default='upload/default.jpg', upload_to='upload/%Y/%m', verbose_name='图片')),
            ],
            options={
                'verbose_name': '网站相册',
                'verbose_name_plural': '网站相册',
            },
        ),
    ]
