# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_siteinfo_site_changyan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='site_changyan',
            field=models.TextField(default='', verbose_name='文章底部广告代码'),
        ),
    ]
