# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20170921_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_original',
            field=models.CharField(choices=[('1', '原创'), ('0', '转载')], default='1', max_length=10, verbose_name='是否原创'),
        ),
    ]
